### ISSUE TITLE
Nice-to-have

### ISSUE THREAD

**Issue by maxrawlinger** [ndrsllwngr/omm#128]
**UX/UI**
- [ ] Loadingstate/icon (Like nian cat flying throw viewport)

**Meme Generator:**
- [ ] Predefined Image filter on Meme creation (Like Instagram)
- [ ] Keyboard interaction while meme creation -> means goback and clear with backspace and enter and copy-paste font-box
- [ ] When choosing colour while meme creation no coloured overlay behind the focused text
- [ ] Text background.
