### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by ndrsllwngr** [ndrsllwngr/omm#182]
##### TODO
- [ ] title input mandatory for templates
- [ ] loading state should be improved
  - skeleton https://material-ui.com/components/skeleton/
  - nyan cat flying through viewport 
- [ ] allow user to choose canvas color (default, transparent)
- [ ] refactor code
- [ ] redesign

---

##### BACKLOG
- [ ] add custom screenshot api to backend with puppeteer
- [ ] allow video only meme
- [ ] allow gif only meme
- [ ] always write template into meme collection, if template is not yet existing, create one. not doing, but should be implemented
- [ ] meme/id page: Being in a state, in which you are looking at a Meme and filter after (e.g.) trending, but the current meme you are looking at is not in this scope, you are still able to enable random autoplay but it is not navigating to a new meme. therefore this meme is not part of the filter results scope, might be strange for the user.
  - Random applies the filters, by design, too. We need to somehow inform the user that he reached a dead end 🗡️
  - maybe notify user? 
- [ ] mitigate duplicate templates (from e.g. imgflip api)
- [ ] add option to set txt background
- [ ] add proper shadows to text
- [ ] include gifs as possible templates (static caption)
- [ ] add option to navigate through pages on overview page (e.g. endless scroll or pagination)
- [ ] add forkedBy entry to meme when it forks a meme 
- /generate - meme generator
  - [ ] Predefined Image filter on Meme creation (Like Instagram)
  - [ ] Keyboard interaction while meme creation -> means goback and clear with backspace and enter and copy-paste font-box
  - [ ] When choosing colour while meme creation no coloured overlay behind the focused text
  - [ ] Text background.
