### ISSUE TITLE
Update README and make project ready for submission

### ISSUE THREAD

**Issue by ndrsllwngr** [ndrsllwngr/omm#40]
- > Please be aware of **copyright or legal issues (for publicly reachable webpages)**, especially if anyone can upload images. Further, **data privacy and GDPR compliance** should be considered (it is not required, but you should mention it) as the use of web services is easier and scalable but one does give up control over the websites data to various degrees.
- > For all used technologies, it still holds (as described in the project description), that **you have to specify the license and function of the integrated library/function.** E.g. if you use the user management in firebase you need to explain in the code/comments **what happens internally (how/where (e.g. country) does firebase store data (data privacy!)**, what are my options to create/retrieve users, etc.). This does not need to be a two page in-depth analysis, but you should understand what you are using and inform yourself about it.
- > For the hand-in we **require a “reproducible” and a “live” version**. In case of a local server, container or similar both are fulfilled by the submission being executable. In case we cannot just locally execute your server and access the webpage, please provide a link to a live version to try the website out. This can also be a local webpage with an online server as backend.
provide `.env.local` with credentials
- > Please **provide a readme file and sufficient instructions to run the webpage/server and or recreate all no local parts.** This also means, that all necessary code has to be submitted. If code is normally not in a file structure (e.g. web interface of a web service) you have to submit the code as text files. The readme could look like: “Register for MongoDB Atlas, create a database name “XX”, import file “dump.json”, adjust login credentials in file “dblogin.js”. Run this in node.js, open http://localhost:3000/” Or **“register to firebase, create new app, create server less task with condition X and copy code from file XY.txt**
- > **All information for us to be are able to “copy” everything to a new server/account without previous knowledge has to be included.**
- > If not all your features are reachable from the index page, please also **include either an overview page or list features in the readme** (e.g. open http://localhost:3000/ for webpage and use http://localhost:3000/api for the API requests). However, an overview page (as part of your website) with an example API call and links to the individual pages is preferred for faster evaluation.

### TODO
- [ ] refactor code
- [x] comment code
- [x] test run project
- [x] add option to start project within a docker image ❗
- [x] create documentation regarding setup of firebase and mongodb ❗
- [x] fill out the excel sheet with points and add additional points ❗

### FINAL SUBMISSION
- [x] soruce code
- [x] readme (step by step how to set up)
- [x] env files
- [x] add online service document (google)
- [x] link to hosted live version
- [x] docker container hochladen und link mitgeben
- [x] feature list (excel sheet)
- [x] add to readme easy instructions
- [x] add liscense of all depdencies list
- [x] postman collection im readme referenzieren (für API)
- [x] sitemap of all pages and routes (take output of next build)
