### ISSUE TITLE
TODOs Andreas E.

### ISSUE THREAD

**Issue by ndrsllwngr** [ndrsllwngr/omm#76]
#### BACKLOG
- [ ] mitigate duplicate templates (from e.g. imgflip api)
- [ ] loading skeleton https://material-ui.com/components/skeleton/
- [ ] allow user to choose canvas color (default, transparent)
- [ ] meme/id wont load if only 1 meme collection size equals 1
- [ ] add option to set txt background
- [ ] add proper shadows to text
- [ ] title input mandatory for templates
- [ ] include gifs as possible templates (static caption) _not doing_

#### TODO
- [ ] add option to navigate through pages on overview page (e.g. endless scroll or pagination)
- [x] add option to generate memes server-side (just send all data to route, insert into db on backend)
- download meme
  - [x] add option to choose generated file size of download (before generation), sync with @griase94 
  - [x] add option to generate png output
  - [x] add download buttons (client/server)
  - [x] use route of andy with api to download meme (with query param)
- [ ] add forkedBy entry to meme when it forks a meme 
- [x] include videos as possible templates (static caption)
- [x] write automated tests
- [ ] refactor code
- [x] comment code
- [x] check readme
- [x] check docker image
- [x] fill out task list (excel sheet) and add additional points
- [x] upload latest git repo/excel sheet, readme, instructions, docker image (link to zip file)

---

#### DONE
- [x] add captions to root key/val of meme & and add them to text to speech
- [x] enable filter by template on /meme/id page
- [x] add charts to meme page (as modal) similar to template details
- [x] move template input modals to meme generator
- [x] add text to speech to meme/id page
- [x] add speech to text to meme generator (input caption / title)
- [x] fix charts of template details
- [x] add charts to templates (as modal)
- [x] evaluate template value in meme collection, and necessary template content in template collection
- [x] inject title, too when copying meme and opening a draft
- [x] add option to change visibility level to public/unlisted
- [x] remove draft collection
- [x] allow for dictating captions
- [x] after creating a template and navigating to meme/create a hard reload is triggered
- [x] Fix autoplay
- [x] Implement UI for comments
- [x] fix template webcam bug, if permission is missing (video.srcObject)
- [x] Load fonts via font-loader to support e.g. mobile 💔  use default google font imports instead
- [x] add option resize canvas
- [x] reset filter on meme generate :)
- [x] add share buttons
- [x] Update proptypes (meme)
- [x] ~Fix bug to using a meme of imgflip api in meme generator~ I am unable to reproduce this issue. 💔 
- [x] title in load meme state
- [x] fix loading state in /index
- [x] update env vars on vercel
