### ISSUE TITLE
TODOs Andy

### ISSUE THREAD

**Issue by ndrsllwngr** [ndrsllwngr/omm#77]
##### TODO
- [x] add option to generate meme in backend (get the complete json)❗ 
- [x] add option to start project within a docker image ❗ 
- [x] create documentation regarding setup of firebase and mongodb ❗ 
- [x] fill out the excel sheet with points and add additional points ❗ 
- [ ] add custom screenshot api to backend with puppeteer

##### DONE
- [x] add fabric js to backend
- [x] comment (add custom resolver, add comment selection, add comment count)
- [x] fix all api routes
- [x] user bound kommentar funktion bei memes
- [x] insert user data on registration
- [x] add point count (aka difference between up and down votes, see `getTotalPoints`)
- [x] meme view count hochzählen (cheating verhindern)
- [x] ~das system bzgl. public/unlisted/private memes umsetzen (feld wird bereits bei creation gesetzt)~ #100 
- [x] ~bei den votes die anzahl von votes anzeigen~ #78 #80 
- [x] ~evtl. onSnapshot usw bei useVoting wegnehmen, da die Memes sowieso mit einem onSnapshot angezeigt werden, und somit useVoting nur mit writes umsetzen ohne reads, würde somit db usage um N verringern~ #78  #80
